#############################################################################
# Makefile for building: qtFlacSchlonz
# Generated by qmake (2.01a) (Qt 4.8.2) on: Sun Sep 28 18:42:45 2014
# Project:  flacshlonz.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile flacshlonz.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lFLAC++ -lQtMultimedia -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		FileSystemManager.cpp \
		FlacMetaDataManager.cpp \
		StatusBar.cpp \
		Utils.cpp \
		FileSystemModel.cpp \
		Persistence.cpp \
		ConfigDialog.cpp \
		ConfigPageAlgorithm.cpp \
		ConfigPageGeneral.cpp \
		ThreadFlacScanner.cpp \
		ThreadRemoveFiles.cpp \
		ThreadCopyFiles.cpp \
		DataBase.cpp \
		FreeDiskStorage.cpp \
		ThreadDataBaseImport.cpp \
		Application.cpp \
		MetaDataKeys.cpp \
		StringEncodingWin.cpp \
		player/Player.cpp \
		player/VideoWidget.cpp moc_MainWindow.cpp \
		moc_FileSystemManager.cpp \
		moc_StatusBar.cpp \
		moc_FileSystemModel.cpp \
		moc_ConfigDialog.cpp \
		moc_ConfigPageAlgorithm.cpp \
		moc_ConfigPageGeneral.cpp \
		moc_ThreadFlacScanner.cpp \
		moc_ThreadRemoveFiles.cpp \
		moc_ThreadCopyFiles.cpp \
		moc_DataBase.cpp \
		moc_ThreadDataBaseImport.cpp \
		moc_Application.cpp \
		moc_Player.cpp \
		moc_VideoWidget.cpp \
		qrc_flacshlonz.cpp
OBJECTS       = main.o \
		MainWindow.o \
		FileSystemManager.o \
		FlacMetaDataManager.o \
		StatusBar.o \
		Utils.o \
		FileSystemModel.o \
		Persistence.o \
		ConfigDialog.o \
		ConfigPageAlgorithm.o \
		ConfigPageGeneral.o \
		ThreadFlacScanner.o \
		ThreadRemoveFiles.o \
		ThreadCopyFiles.o \
		DataBase.o \
		FreeDiskStorage.o \
		ThreadDataBaseImport.o \
		Application.o \
		MetaDataKeys.o \
		StringEncodingWin.o \
		Player.o \
		VideoWidget.o \
		moc_MainWindow.o \
		moc_FileSystemManager.o \
		moc_StatusBar.o \
		moc_FileSystemModel.o \
		moc_ConfigDialog.o \
		moc_ConfigPageAlgorithm.o \
		moc_ConfigPageGeneral.o \
		moc_ThreadFlacScanner.o \
		moc_ThreadRemoveFiles.o \
		moc_ThreadCopyFiles.o \
		moc_DataBase.o \
		moc_ThreadDataBaseImport.o \
		moc_Application.o \
		moc_Player.o \
		moc_VideoWidget.o \
		qrc_flacshlonz.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		flacshlonz.pro
QMAKE_TARGET  = qtFlacSchlonz
DESTDIR       = 
TARGET        = qtFlacSchlonz

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: flacshlonz.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtXml.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile flacshlonz.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtXml.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile flacshlonz.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtFlacSchlonz1.0.0 || $(MKDIR) .tmp/qtFlacSchlonz1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtFlacSchlonz1.0.0/ && $(COPY_FILE) --parents MainWindow.hpp FileSystemManager.hpp FlacMetaDataManager.hpp FlacTrack.hpp StatusBar.hpp Utils.hpp FileSystemModel.hpp Persistence.hpp ConfigDialog.hpp ConfigPageAlgorithm.hpp ConfigPageGeneral.hpp ThreadFlacScanner.hpp ThreadRemoveFiles.hpp ThreadCopyFiles.hpp DataBase.hpp FreeDiskStorage.hpp ThreadDataBaseImport.hpp Application.hpp StringEncodingWin.hpp MetaDataKeys.hpp player/Player.hpp player/VideoWidget.hpp .tmp/qtFlacSchlonz1.0.0/ && $(COPY_FILE) --parents flacshlonz.qrc .tmp/qtFlacSchlonz1.0.0/ && $(COPY_FILE) --parents main.cpp MainWindow.cpp FileSystemManager.cpp FlacMetaDataManager.cpp StatusBar.cpp Utils.cpp FileSystemModel.cpp Persistence.cpp ConfigDialog.cpp ConfigPageAlgorithm.cpp ConfigPageGeneral.cpp ThreadFlacScanner.cpp ThreadRemoveFiles.cpp ThreadCopyFiles.cpp DataBase.cpp FreeDiskStorage.cpp ThreadDataBaseImport.cpp Application.cpp MetaDataKeys.cpp StringEncodingWin.cpp player/Player.cpp player/VideoWidget.cpp .tmp/qtFlacSchlonz1.0.0/ && (cd `dirname .tmp/qtFlacSchlonz1.0.0` && $(TAR) qtFlacSchlonz1.0.0.tar qtFlacSchlonz1.0.0 && $(COMPRESS) qtFlacSchlonz1.0.0.tar) && $(MOVE) `dirname .tmp/qtFlacSchlonz1.0.0`/qtFlacSchlonz1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtFlacSchlonz1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp moc_FileSystemManager.cpp moc_StatusBar.cpp moc_FileSystemModel.cpp moc_ConfigDialog.cpp moc_ConfigPageAlgorithm.cpp moc_ConfigPageGeneral.cpp moc_ThreadFlacScanner.cpp moc_ThreadRemoveFiles.cpp moc_ThreadCopyFiles.cpp moc_DataBase.cpp moc_ThreadDataBaseImport.cpp moc_Application.cpp moc_Player.cpp moc_VideoWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_FileSystemManager.cpp moc_StatusBar.cpp moc_FileSystemModel.cpp moc_ConfigDialog.cpp moc_ConfigPageAlgorithm.cpp moc_ConfigPageGeneral.cpp moc_ThreadFlacScanner.cpp moc_ThreadRemoveFiles.cpp moc_ThreadCopyFiles.cpp moc_DataBase.cpp moc_ThreadDataBaseImport.cpp moc_Application.cpp moc_Player.cpp moc_VideoWidget.cpp
moc_MainWindow.cpp: FileSystemModel.hpp \
		FlacMetaDataManager.hpp \
		Utils.hpp \
		FlacTrack.hpp \
		MetaDataKeys.hpp \
		FileSystemManager.hpp \
		Persistence.hpp \
		ThreadFlacScanner.hpp \
		ThreadRemoveFiles.hpp \
		ThreadCopyFiles.hpp \
		DataBase.hpp \
		ThreadDataBaseImport.hpp \
		ConfigDialog.hpp \
		ConfigPageGeneral.hpp \
		ConfigPageAlgorithm.hpp \
		MainWindow.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.hpp -o moc_MainWindow.cpp

moc_FileSystemManager.cpp: FlacTrack.hpp \
		Persistence.hpp \
		ThreadFlacScanner.hpp \
		ThreadRemoveFiles.hpp \
		ThreadCopyFiles.hpp \
		DataBase.hpp \
		Utils.hpp \
		ThreadDataBaseImport.hpp \
		FileSystemManager.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FileSystemManager.hpp -o moc_FileSystemManager.cpp

moc_StatusBar.cpp: StatusBar.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) StatusBar.hpp -o moc_StatusBar.cpp

moc_FileSystemModel.cpp: FileSystemModel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FileSystemModel.hpp -o moc_FileSystemModel.cpp

moc_ConfigDialog.cpp: ConfigPageGeneral.hpp \
		Persistence.hpp \
		ConfigPageAlgorithm.hpp \
		ConfigDialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ConfigDialog.hpp -o moc_ConfigDialog.cpp

moc_ConfigPageAlgorithm.cpp: Persistence.hpp \
		ConfigPageAlgorithm.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ConfigPageAlgorithm.hpp -o moc_ConfigPageAlgorithm.cpp

moc_ConfigPageGeneral.cpp: Persistence.hpp \
		ConfigPageGeneral.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ConfigPageGeneral.hpp -o moc_ConfigPageGeneral.cpp

moc_ThreadFlacScanner.cpp: Persistence.hpp \
		ThreadFlacScanner.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ThreadFlacScanner.hpp -o moc_ThreadFlacScanner.cpp

moc_ThreadRemoveFiles.cpp: ThreadRemoveFiles.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ThreadRemoveFiles.hpp -o moc_ThreadRemoveFiles.cpp

moc_ThreadCopyFiles.cpp: ThreadCopyFiles.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ThreadCopyFiles.hpp -o moc_ThreadCopyFiles.cpp

moc_DataBase.cpp: Utils.hpp \
		FlacTrack.hpp \
		DataBase.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) DataBase.hpp -o moc_DataBase.cpp

moc_ThreadDataBaseImport.cpp: DataBase.hpp \
		Utils.hpp \
		FlacTrack.hpp \
		Persistence.hpp \
		ThreadDataBaseImport.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ThreadDataBaseImport.hpp -o moc_ThreadDataBaseImport.cpp

moc_Application.cpp: MainWindow.hpp \
		FileSystemModel.hpp \
		FlacMetaDataManager.hpp \
		Utils.hpp \
		FlacTrack.hpp \
		MetaDataKeys.hpp \
		FileSystemManager.hpp \
		Persistence.hpp \
		ThreadFlacScanner.hpp \
		ThreadRemoveFiles.hpp \
		ThreadCopyFiles.hpp \
		DataBase.hpp \
		ThreadDataBaseImport.hpp \
		ConfigDialog.hpp \
		ConfigPageGeneral.hpp \
		ConfigPageAlgorithm.hpp \
		Application.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Application.hpp -o moc_Application.cpp

moc_Player.cpp: player/VideoWidget.hpp \
		player/Player.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) player/Player.hpp -o moc_Player.cpp

moc_VideoWidget.cpp: player/VideoWidget.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) player/VideoWidget.hpp -o moc_VideoWidget.cpp

compiler_rcc_make_all: qrc_flacshlonz.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_flacshlonz.cpp
qrc_flacshlonz.cpp: flacshlonz.qrc \
		images/icon2.png \
		images/about.png
	/usr/bin/rcc -name flacshlonz flacshlonz.qrc -o qrc_flacshlonz.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp MainWindow.hpp \
		FileSystemModel.hpp \
		FlacMetaDataManager.hpp \
		Utils.hpp \
		FlacTrack.hpp \
		MetaDataKeys.hpp \
		FileSystemManager.hpp \
		Persistence.hpp \
		ThreadFlacScanner.hpp \
		ThreadRemoveFiles.hpp \
		ThreadCopyFiles.hpp \
		DataBase.hpp \
		ThreadDataBaseImport.hpp \
		ConfigDialog.hpp \
		ConfigPageGeneral.hpp \
		ConfigPageAlgorithm.hpp \
		Application.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.hpp \
		FileSystemModel.hpp \
		FlacMetaDataManager.hpp \
		Utils.hpp \
		FlacTrack.hpp \
		MetaDataKeys.hpp \
		FileSystemManager.hpp \
		Persistence.hpp \
		ThreadFlacScanner.hpp \
		ThreadRemoveFiles.hpp \
		ThreadCopyFiles.hpp \
		DataBase.hpp \
		ThreadDataBaseImport.hpp \
		ConfigDialog.hpp \
		ConfigPageGeneral.hpp \
		ConfigPageAlgorithm.hpp \
		StatusBar.hpp \
		FreeDiskStorage.hpp \
		player/Player.hpp \
		player/VideoWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

FileSystemManager.o: FileSystemManager.cpp FileSystemManager.hpp \
		FlacTrack.hpp \
		Persistence.hpp \
		ThreadFlacScanner.hpp \
		ThreadRemoveFiles.hpp \
		ThreadCopyFiles.hpp \
		DataBase.hpp \
		Utils.hpp \
		ThreadDataBaseImport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileSystemManager.o FileSystemManager.cpp

FlacMetaDataManager.o: FlacMetaDataManager.cpp FlacMetaDataManager.hpp \
		Utils.hpp \
		FlacTrack.hpp \
		MetaDataKeys.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FlacMetaDataManager.o FlacMetaDataManager.cpp

StatusBar.o: StatusBar.cpp StatusBar.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StatusBar.o StatusBar.cpp

Utils.o: Utils.cpp Utils.hpp \
		FlacTrack.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utils.o Utils.cpp

FileSystemModel.o: FileSystemModel.cpp FileSystemModel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileSystemModel.o FileSystemModel.cpp

Persistence.o: Persistence.cpp Persistence.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Persistence.o Persistence.cpp

ConfigDialog.o: ConfigDialog.cpp ConfigDialog.hpp \
		ConfigPageGeneral.hpp \
		Persistence.hpp \
		ConfigPageAlgorithm.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigDialog.o ConfigDialog.cpp

ConfigPageAlgorithm.o: ConfigPageAlgorithm.cpp ConfigPageAlgorithm.hpp \
		Persistence.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigPageAlgorithm.o ConfigPageAlgorithm.cpp

ConfigPageGeneral.o: ConfigPageGeneral.cpp ConfigPageGeneral.hpp \
		Persistence.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigPageGeneral.o ConfigPageGeneral.cpp

ThreadFlacScanner.o: ThreadFlacScanner.cpp ThreadFlacScanner.hpp \
		Persistence.hpp \
		FlacTrack.hpp \
		FlacMetaDataManager.hpp \
		Utils.hpp \
		MetaDataKeys.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThreadFlacScanner.o ThreadFlacScanner.cpp

ThreadRemoveFiles.o: ThreadRemoveFiles.cpp ThreadRemoveFiles.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThreadRemoveFiles.o ThreadRemoveFiles.cpp

ThreadCopyFiles.o: ThreadCopyFiles.cpp ThreadCopyFiles.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThreadCopyFiles.o ThreadCopyFiles.cpp

DataBase.o: DataBase.cpp DataBase.hpp \
		Utils.hpp \
		FlacTrack.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataBase.o DataBase.cpp

FreeDiskStorage.o: FreeDiskStorage.cpp FreeDiskStorage.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FreeDiskStorage.o FreeDiskStorage.cpp

ThreadDataBaseImport.o: ThreadDataBaseImport.cpp ThreadDataBaseImport.hpp \
		DataBase.hpp \
		Utils.hpp \
		FlacTrack.hpp \
		Persistence.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThreadDataBaseImport.o ThreadDataBaseImport.cpp

Application.o: Application.cpp Application.hpp \
		MainWindow.hpp \
		FileSystemModel.hpp \
		FlacMetaDataManager.hpp \
		Utils.hpp \
		FlacTrack.hpp \
		MetaDataKeys.hpp \
		FileSystemManager.hpp \
		Persistence.hpp \
		ThreadFlacScanner.hpp \
		ThreadRemoveFiles.hpp \
		ThreadCopyFiles.hpp \
		DataBase.hpp \
		ThreadDataBaseImport.hpp \
		ConfigDialog.hpp \
		ConfigPageGeneral.hpp \
		ConfigPageAlgorithm.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Application.o Application.cpp

MetaDataKeys.o: MetaDataKeys.cpp MetaDataKeys.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MetaDataKeys.o MetaDataKeys.cpp

StringEncodingWin.o: StringEncodingWin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StringEncodingWin.o StringEncodingWin.cpp

Player.o: player/Player.cpp player/Player.hpp \
		player/VideoWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o player/Player.cpp

VideoWidget.o: player/VideoWidget.cpp player/VideoWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VideoWidget.o player/VideoWidget.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_FileSystemManager.o: moc_FileSystemManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FileSystemManager.o moc_FileSystemManager.cpp

moc_StatusBar.o: moc_StatusBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StatusBar.o moc_StatusBar.cpp

moc_FileSystemModel.o: moc_FileSystemModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FileSystemModel.o moc_FileSystemModel.cpp

moc_ConfigDialog.o: moc_ConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ConfigDialog.o moc_ConfigDialog.cpp

moc_ConfigPageAlgorithm.o: moc_ConfigPageAlgorithm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ConfigPageAlgorithm.o moc_ConfigPageAlgorithm.cpp

moc_ConfigPageGeneral.o: moc_ConfigPageGeneral.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ConfigPageGeneral.o moc_ConfigPageGeneral.cpp

moc_ThreadFlacScanner.o: moc_ThreadFlacScanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ThreadFlacScanner.o moc_ThreadFlacScanner.cpp

moc_ThreadRemoveFiles.o: moc_ThreadRemoveFiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ThreadRemoveFiles.o moc_ThreadRemoveFiles.cpp

moc_ThreadCopyFiles.o: moc_ThreadCopyFiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ThreadCopyFiles.o moc_ThreadCopyFiles.cpp

moc_DataBase.o: moc_DataBase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DataBase.o moc_DataBase.cpp

moc_ThreadDataBaseImport.o: moc_ThreadDataBaseImport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ThreadDataBaseImport.o moc_ThreadDataBaseImport.cpp

moc_Application.o: moc_Application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Application.o moc_Application.cpp

moc_Player.o: moc_Player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Player.o moc_Player.cpp

moc_VideoWidget.o: moc_VideoWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VideoWidget.o moc_VideoWidget.cpp

qrc_flacshlonz.o: qrc_flacshlonz.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_flacshlonz.o qrc_flacshlonz.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

